### ISSUE TITLE
Cant turn on/off anymore from HA

### ISSUE THREAD

**Issue by FSHelgeland** [JohNan/homeassistant-wellbeing#160]
Not sure for how long this has been going on, but I suspect it is after I updated HA core to 2025.1.02b. I have several automation running turning my A9 on/off, but now I get an error telling me fan mode on/off is not supported. 

`Logger: homeassistant.components.websocket_api.http.connection
Kilde: components/websocket_api/commands.py:287
integrasjon: Home Assistant WebSocket API (dokumentasjon, problemer)
Første forekomst: 10:50:42 (11 forekomster)
Sist logget: 10:54:41

[546354480032] Entity fan.wellbeing_luftrenser_stue_fanspeed does not support action fan.turn_on
[546354480032] Entity fan.wellbeing_luftrenser_stue_fanspeed does not support action fan.turn_off`

**Comment by DavidSchischke** [comment]
Facing the same issue with an A7, also on 2025.1.

**Comment by PsychoV3** [comment]
Just use set preset PowerOff:

```
action: fan.set_preset_mode
target:
  entity_id:
    - fan.wellbeing_air_purifier_fanspeed
    - fan.wellbeing_office_air_purifier_fanspeed
data:
  preset_mode: PowerOff
enabled: true
```

Don't think there is an issue here.
